<?php
/**
 * Installer.
 *
 * @param array		$requirements
 * @param bool		$errors
 * @param bool		$warnings
 * @param bool		$installed
 */
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: s-maxage=0, max-age=0, must-revalidate');
header('Expires: Mon, 23 Jan 1978 10:00:00 GMT');
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="robots" content="noindex">
	<meta name="description" content="">
    <meta name="author" content="">

	<title>Installer</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="<?php echo ROOT_PATH; ?>/assets/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
	  #footer {
		  background-color: #f5f5f5;
		  height: 60px;
	  }

	   /* Custom page CSS
      -------------------------------------------------- */

      .container {
        width: auto;
        max-width: 680px;
      }
      .container .credit {
        margin: 20px 0;
      }
    </style>
	<link href="<?php echo ROOT_PATH; ?>/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="<?php echo ROOT_PATH; ?>/assets/js/html5shiv.js"></script>
    <![endif]-->

</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="brand" href="<?php Template::link() ?>">Installer</a>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li class="active"><a href="<?php echo ROOT_PATH; ?>">Home</a></li>
						<li><a href="<?php echo ROOT_PATH; ?>/check">Check</a></li>
						<li><a href="<?php echo ROOT_PATH; ?>/install">Install</a></li>
						<li><a href="<?php echo ROOT_PATH; ?>/update">Update</a></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<?php if($flashes = $this->flashes()): ?>
			<?php foreach($flashes as $type => $messages): ?>
				<?php foreach($messages as $msq): ?>
		<div class="alert alert-<?php echo $type; ?>">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<?php echo $msq; ?><br>
		</div>
				<?php endforeach ?>
			<?php endforeach ?>
		<?php endif ?>

		<?php $this->yield(); //The view is rendered here  ?>
	</div> <!-- /container -->

	<footer id="footer">
		<div class="container">
			<p class="muted credit"><small>Installer <?php echo INSTALLER_VERSION ?></small></p>
		</div>
	</footer>

	<script src="http://code.jquery.com/jquery.js"></script>
	<script src="<?php echo ROOT_PATH; ?>/assets/js/bootstrap.min.js"></script>
</body>
</html>
