<form method='post'>
	<fieldset>
	<p>
		<label for='server'>Server Address</label>
		<input type='text' name='server'>
	</p>
	<p>
		<label for='database'>Database name</label>
		<input type='text' name='database'>
	</p>
	<p>
		<label for='user'>User name</label>
		<input type='text' name='user'>
	</p>
	<p>
		<label for='password'>Password</label>
		<input type='password' name='password'>
	</p>
	<p>
		<input type='submit' name='send' value='Odeslat' class='btn btn-primary'>
	</p>
	</fieldset>
</form>